name: Deploy ElasticStar

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: [ self-hosted, kubernetes, bristol ]
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: kubectl
        run: kubectl apply -f kubernetes-deployment.yml