name: Populate Elastic Cloud

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  populate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv elasticsearch tqdm

      - name: Run main script
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
          ELASTIC_CLOUD_PASSWORD: ${{ secrets.ELASTIC_CLOUD_PASSWORD }}
        run: python main.py