name: Populate elastic

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  populate-data:
    runs-on: github-runners-elasticstar
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BUSINESS_ACCESS_TOKEN: ${{ secrets.BUSINESS_ACCESS_TOKEN }}
          JOINT_ACCESS_TOKEN: ${{ secrets.JOINT_ACCESS_TOKEN }}
          ELASTIC_HOST: ${{ secrets.HOST }}
          ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
        run: python starling_to_elastic.py
