name: Terraform Cloud Workflow

on:
  push:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Terraform Cloud
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.ATLAS_TOKEN }}

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply --auto-approve