name: Terraform Cloud Workflow

on:
  push:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Terraform Cloud
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.ATLAS_TOKEN }}
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Initialise
        working-directory: terraform
        run: terraform init

      - name: Plan
        working-directory: terraform
        run: terraform plan

      - name: Apply
        working-directory: terraform
        run: terraform apply --auto-approve