name: Provision Elastic Cloud deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  schedule:
    - cron: "* * * * *"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Terraform Cloud
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_KEY }}
          terraform_wrapper: false

      - name: Initialise
        working-directory: terraform
        run: terraform init

      - name: Apply
        working-directory: terraform
        run: terraform apply --auto-approve -var="elastic_api_key=${{ secrets.ELASTIC_API_KEY }}" -var="github_api_key=${{ secrets.SECRETS_GITHUB_API_KEY }}"
