name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/elastic-star

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

  deploy:
    runs-on: [ self-hosted, kubernetes, bristol ]
    needs: push_to_registry
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: kubectl
        run: kubectl delete -f kubernetes-deployment.yml

      - name: create-environment-file
        run: echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: create-environment-configmap
        run: kubectl create configmap environment --from-file .env -o yaml --dry-run=client | kubectl apply -f -

      - name: kubectl
        run: kubectl apply -f kubernetes-deployment.yml