name: Populate Data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install    
        
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run main.py
