name: Populate Data

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install

      - name: Google service account file creation
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python decodeServiceAccount.py

      - name: Run main script
        env:
          SHEET_NAME_TRANSACTION_HISTORY: "Starling Account"
          SHEET_NAME_SAVING_SPACES: "Starling Spaces"
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          WORKBOOK_ID: ${{ secrets.WORKBOOK_ID }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python main.py
